//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyTourney.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBEasyTourneyEntities : DbContext
    {
        public DBEasyTourneyEntities()
            : base("name=DBEasyTourneyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblCategory> tblCategory { get; set; }
        public virtual DbSet<tblEvent> tblEvent { get; set; }
        public virtual DbSet<tblEventMessages> tblEventMessages { get; set; }
        public virtual DbSet<tblEventPreferences> tblEventPreferences { get; set; }
        public virtual DbSet<tblMessage> tblMessage { get; set; }
        public virtual DbSet<tblPreference> tblPreference { get; set; }
        public virtual DbSet<tblRol> tblRol { get; set; }
        public virtual DbSet<tblUser> tblUser { get; set; }
        public virtual DbSet<tblUserEvents> tblUserEvents { get; set; }
        public virtual DbSet<tblUserPreference> tblUserPreference { get; set; }
    }
}
