//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyTourney.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEventPreferences
    {
        public System.Guid GUID { get; set; }
        public Nullable<System.Guid> PreferenceId { get; set; }
        public Nullable<System.Guid> EventId { get; set; }
    
        public virtual tblEvent tblEvent { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
