//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyTourney.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEvent
    {
        public tblEvent()
        {
            this.tblEventMessages = new HashSet<tblEventMessages>();
            this.tblEventPreferences = new HashSet<tblEventPreferences>();
            this.tblUserEvents = new HashSet<tblUserEvents>();
        }
    
        public System.Guid GUID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> StarDate { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public Nullable<int> MaxParticipants { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual ICollection<tblEventMessages> tblEventMessages { get; set; }
        public virtual ICollection<tblEventPreferences> tblEventPreferences { get; set; }
        public virtual ICollection<tblUserEvents> tblUserEvents { get; set; }
    }
}
