//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyTourney.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMessage
    {
        public tblMessage()
        {
            this.tblEventMessages = new HashSet<tblEventMessages>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string Content { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual tblCategory tblCategory { get; set; }
        public virtual ICollection<tblEventMessages> tblEventMessages { get; set; }
    }
}
