//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyTourney.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRol
    {
        public tblRol()
        {
            this.tblUser = new HashSet<tblUser>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<tblUser> tblUser { get; set; }
    }
}
