//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyTourney.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUser
    {
        public tblUser()
        {
            this.tblEventPreferences = new HashSet<tblEventPreferences>();
            this.tblUserEvents = new HashSet<tblUserEvents>();
            this.tblUserPreference = new HashSet<tblUserPreference>();
        }
    
        public System.Guid GUID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public Nullable<System.Guid> RolId { get; set; }
        public string Pass { get; set; }
    
        public virtual ICollection<tblEventPreferences> tblEventPreferences { get; set; }
        public virtual tblRol tblRol { get; set; }
        public virtual ICollection<tblUserEvents> tblUserEvents { get; set; }
        public virtual ICollection<tblUserPreference> tblUserPreference { get; set; }
    }
}
